matches:
  # symbols
  - trigger: "-->"
    replace: "→"
  - trigger: "<--"
    replace: "←"
  - trigger: "<->"
    replace: "⇔"
  - trigger: ".:"
    replace: "∴"
  - trigger: ">="
    replace: "≥"
  - trigger: "<="
    replace: "≤"
  - trigger: "!="
    replace: "≠"
  - trigger: "~="
    replace: "≈"
  - trigger: "+-"
    replace: "±"
  - trigger: ":inf"
    replace: "∞"
  - trigger: ":deg"
    replace: "°"
  # fractions
  - trigger: "1/2"
    replace: "½"
  - trigger: "1/3"
    replace: "⅓"
  - trigger: "2/3"
    replace: "⅔"
  - trigger: "3/4"
    replace: "¾"
  - trigger: "1/4"
    replace: "¼"
