# https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
git:
  pagers:
    - pager: delta --dark --paging=never
      colorArg: always
    - externalDiffCommand: difft --color=always
    # Press pipe | to cycle between diff tools in LazyGit
